--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-03-09 15:56:09 +03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 16582)
-- Name: Blogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Blogs" (
    "BlogId" integer NOT NULL,
    "BlogTitle" text NOT NULL,
    "BlogContent" text NOT NULL,
    "BlogThumbnailImage" text NOT NULL,
    "BlogImage" text NOT NULL,
    "BlogCreateDate" timestamp with time zone NOT NULL,
    "BlogStatus" boolean NOT NULL,
    "CategoryID" integer NOT NULL,
    "WriterID" integer
);


ALTER TABLE public."Blogs" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16581)
-- Name: Blogs_BlogId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Blogs" ALTER COLUMN "BlogId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Blogs_BlogId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3614 (class 0 OID 16582)
-- Dependencies: 224
-- Data for Name: Blogs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Blogs" ("BlogId", "BlogTitle", "BlogContent", "BlogThumbnailImage", "BlogImage", "BlogCreateDate", "BlogStatus", "CategoryID", "WriterID") FROM stdin;
1	deneme	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur venenatis pretium tincidunt. Fusce condimentum nisl non tempus efficitur. Vestibulum non lectus consectetur, ultricies est a, auctor massa. Aliquam sit amet mauris vitae felis bibendum posuere. Pellentesque eget posuere tellus. Vestibulum vestibulum ipsum ut eros vulputate, vitae mattis sapien sollicitudin. Integer fringilla, neque vitae viverra lobortis, felis felis faucibus turpis, at tincidunt diam elit id urna. Phasellus dignissim purus quis libero malesuada, et blandit lectus pharetra. Praesent et ante vel risus scelerisque porttitor.	deneme	/web/images/b2.jpg	2004-10-19 10:23:54+03	t	1	1
2	deneme	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur venenatis pretium tincidunt. Fusce condimentum nisl non tempus efficitur. Vestibulum non lectus consectetur, ultricies est a, auctor massa. Aliquam sit amet mauris vitae felis bibendum posuere. Pellentesque eget posuere tellus. Vestibulum vestibulum ipsum ut eros vulputate, vitae mattis sapien sollicitudin. Integer fringilla, neque vitae viverra lobortis, felis felis faucibus turpis, at tincidunt diam elit id urna. Phasellus dignissim purus quis libero malesuada, et blandit lectus pharetra. Praesent et ante vel risus scelerisque porttitor.	deneme	/web/images/b3.jpg	2004-10-19 10:23:54+03	t	2	2
3	deneme	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur venenatis pretium tincidunt. Fusce condimentum nisl non tempus efficitur. Vestibulum non lectus consectetur, ultricies est a, auctor massa. Aliquam sit amet mauris vitae felis bibendum posuere. Pellentesque eget posuere tellus. Vestibulum vestibulum ipsum ut eros vulputate, vitae mattis sapien sollicitudin. Integer fringilla, neque vitae viverra lobortis, felis felis faucibus turpis, at tincidunt diam elit id urna. Phasellus dignissim purus quis libero malesuada, et blandit lectus pharetra. Praesent et ante vel risus scelerisque porttitor.	deneme	/web/images/b4.jpg	2004-10-19 10:23:54+03	t	3	3
\.


--
-- TOC entry 3620 (class 0 OID 0)
-- Dependencies: 223
-- Name: Blogs_BlogId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Blogs_BlogId_seq"', 1, false);


--
-- TOC entry 3468 (class 2606 OID 16588)
-- Name: Blogs PK_Blogs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Blogs"
    ADD CONSTRAINT "PK_Blogs" PRIMARY KEY ("BlogId");


--
-- TOC entry 3465 (class 1259 OID 16612)
-- Name: IX_Blogs_CategoryID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Blogs_CategoryID" ON public."Blogs" USING btree ("CategoryID");


--
-- TOC entry 3466 (class 1259 OID 16613)
-- Name: IX_Blogs_WriterID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Blogs_WriterID" ON public."Blogs" USING btree ("WriterID");


--
-- TOC entry 3469 (class 2606 OID 16589)
-- Name: Blogs FK_Blogs_Categories_CategoryID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Blogs"
    ADD CONSTRAINT "FK_Blogs_Categories_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES public."Categories"("CategoryID") ON DELETE CASCADE;


--
-- TOC entry 3470 (class 2606 OID 16594)
-- Name: Blogs FK_Blogs_Writers_WriterID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Blogs"
    ADD CONSTRAINT "FK_Blogs_Writers_WriterID" FOREIGN KEY ("WriterID") REFERENCES public."Writers"("WriterID") ON DELETE CASCADE;


-- Completed on 2023-03-09 15:56:09 +03

--
-- PostgreSQL database dump complete
--

