--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-03-09 16:00:01 +03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16558)
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "CategoryID" integer NOT NULL,
    "CategoryName" text NOT NULL,
    "CategoryDescription" text NOT NULL,
    "CategoryStatus" boolean NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16557)
-- Name: Categories_CategoryID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "CategoryID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_CategoryID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3610 (class 0 OID 16558)
-- Dependencies: 218
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categories" ("CategoryID", "CategoryName", "CategoryDescription", "CategoryStatus") FROM stdin;
1	deneme	deneme	t
2	deneme	deneme	t
3	deneme	deneme	t
\.


--
-- TOC entry 3616 (class 0 OID 0)
-- Dependencies: 217
-- Name: Categories_CategoryID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categories_CategoryID_seq"', 1, false);


--
-- TOC entry 3466 (class 2606 OID 16564)
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryID");


-- Completed on 2023-03-09 16:00:01 +03

--
-- PostgreSQL database dump complete
--

