--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-03-09 16:00:45 +03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16574)
-- Name: Writers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Writers" (
    "WriterID" integer NOT NULL,
    "WriterName" text NOT NULL,
    "WriterAbout" text NOT NULL,
    "WriterImage" text NOT NULL,
    "WriterMail" text NOT NULL,
    "WriterPassword" text NOT NULL,
    "WriterStatus" boolean NOT NULL
);


ALTER TABLE public."Writers" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16573)
-- Name: Writers_WriterID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Writers" ALTER COLUMN "WriterID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Writers_WriterID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3610 (class 0 OID 16574)
-- Dependencies: 222
-- Data for Name: Writers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Writers" ("WriterID", "WriterName", "WriterAbout", "WriterImage", "WriterMail", "WriterPassword", "WriterStatus") FROM stdin;
2	deneme	deneme	deneme	deneme	deneme	t
1	deneme1	deneme1	deneme1	deneme1@gmail.com	deneme1	t
3	deneme2	deneme2	deneme2	deneme2	deneme2	t
\.


--
-- TOC entry 3616 (class 0 OID 0)
-- Dependencies: 221
-- Name: Writers_WriterID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Writers_WriterID_seq"', 1, false);


--
-- TOC entry 3466 (class 2606 OID 16580)
-- Name: Writers PK_Writers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Writers"
    ADD CONSTRAINT "PK_Writers" PRIMARY KEY ("WriterID");


-- Completed on 2023-03-09 16:00:45 +03

--
-- PostgreSQL database dump complete
--

